"""work table

Revision ID: 092e59b0e3b5
Revises: 5e86b4a68354
Create Date: 2019-05-04 20:09:19.035784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '092e59b0e3b5'
down_revision = '5e86b4a68354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('end_of_week', sa.Boolean(), nullable=True))
    op.add_column('work', sa.Column('other_work', sa.DateTime(), nullable=True))
    op.add_column('work', sa.Column('poa', sa.DateTime(), nullable=True))
    op.add_column('work', sa.Column('total_rest', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'total_rest')
    op.drop_column('work', 'poa')
    op.drop_column('work', 'other_work')
    op.drop_column('work', 'end_of_week')
    # ### end Alembic commands ###
