"""work table

Revision ID: 5e86b4a68354
Revises: f1ed8c100ceb
Create Date: 2019-05-04 16:07:21.717274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e86b4a68354'
down_revision = 'f1ed8c100ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('breaks', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'breaks')
    # ### end Alembic commands ###
