"""empty message

Revision ID: 7614f346a0d2
Revises: 8d31449b9d14
Create Date: 2019-05-08 03:29:24.551842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7614f346a0d2'
down_revision = '8d31449b9d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('start_of_week', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'start_of_week')
    # ### end Alembic commands ###
