"""work table

Revision ID: 85d3fc2ddfbc
Revises: 4a57143c662a
Create Date: 2019-04-28 00:29:27.086127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d3fc2ddfbc'
down_revision = '4a57143c662a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holiday_sick', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work')
    # ### end Alembic commands ###
