"""empty message

Revision ID: 8d31449b9d14
Revises: d2c34cd23397
Create Date: 2019-05-08 01:04:03.947062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d31449b9d14'
down_revision = 'd2c34cd23397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('utc_plusone', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'utc_plusone')
    # ### end Alembic commands ###
