"""work table

Revision ID: a91dc139cb2e
Revises: 20901ee8e064
Create Date: 2019-04-30 16:20:59.731146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91dc139cb2e'
down_revision = '20901ee8e064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('driving_hours', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'driving_hours')
    # ### end Alembic commands ###
