"""work table

Revision ID: d2c34cd23397
Revises: 092e59b0e3b5
Create Date: 2019-05-05 02:35:23.109028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c34cd23397'
down_revision = '092e59b0e3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('end_of_shift', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'end_of_shift')
    # ### end Alembic commands ###
