"""empty message

Revision ID: d88160dc800c
Revises: 
Create Date: 2019-05-05 20:23:03.568051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2c34cd23397'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('breaks', sa.String(length=64), nullable=True))
    op.add_column('work', sa.Column('end_of_shift', sa.Boolean(), nullable=True))
    op.add_column('work', sa.Column('end_of_week', sa.Boolean(), nullable=True))
    op.add_column('work', sa.Column('other_work', sa.DateTime(), nullable=True))
    op.add_column('work', sa.Column('poa', sa.DateTime(), nullable=True))
    op.add_column('work', sa.Column('total_rest', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'total_rest')
    op.drop_column('work', 'poa')
    op.drop_column('work', 'other_work')
    op.drop_column('work', 'end_of_week')
    op.drop_column('work', 'end_of_shift')
    op.drop_column('work', 'breaks')
    # ### end Alembic commands ###
