"""work table

Revision ID: f1ed8c100ceb
Revises: a91dc139cb2e
Create Date: 2019-05-01 17:32:21.477289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1ed8c100ceb'
down_revision = 'a91dc139cb2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work', sa.Column('week_beginning', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('work', 'week_beginning')
    # ### end Alembic commands ###
